open! Core

let%expect_test "Extension names" =
  Ppx_log_kernel.For_testing.extension_names
  |> List.sort ~compare:[%compare: string]
  |> List.iter ~f:print_endline;
  [%expect
    {|
    @log
    @log.debug
    @log.debug_format
    @log.debug_raw
    @log.debug_sexp
    @log.debug_string
    @log.error
    @log.error_format
    @log.error_raw
    @log.error_sexp
    @log.error_string
    @log.format
    @log.global
    @log.global.debug
    @log.global.debug_format
    @log.global.debug_raw
    @log.global.debug_sexp
    @log.global.debug_string
    @log.global.error
    @log.global.error_format
    @log.global.error_raw
    @log.global.error_sexp
    @log.global.error_string
    @log.global.format
    @log.global.info
    @log.global.info_format
    @log.global.info_raw
    @log.global.info_sexp
    @log.global.info_string
    @log.global.raw
    @log.global.sexp
    @log.global.string
    @log.info
    @log.info_format
    @log.info_raw
    @log.info_sexp
    @log.info_string
    @log.raw
    @log.sexp
    @log.string
    @log.t
    @log.t.debug
    @log.t.debug_format
    @log.t.debug_raw
    @log.t.debug_sexp
    @log.t.debug_string
    @log.t.error
    @log.t.error_format
    @log.t.error_raw
    @log.t.error_sexp
    @log.t.error_string
    @log.t.format
    @log.t.info
    @log.t.info_format
    @log.t.info_raw
    @log.t.info_sexp
    @log.t.info_string
    @log.t.raw
    @log.t.sexp
    @log.t.string
    |}]
;;
